CHAPTER 8:
# Modélisation et analyse évoluées {#advancedModelling}

De nombreux chercheurs ont élaboré des outils évolués pour l’analyse de données sur les déplacements et les comportements d’animaux en utilisant Motus, comme la triangulation; l’erreur de position (planimétrique) et la probabilité de détection; la modélisation espace-état de déplacements; et calcul des cycles de vie d’émetteurs (durée des haltes, déplacements entre sites subséquents, etc.). Des aspects de certains de ces processus ont été abordés dans des chapitres précédents. Les chercheurs qui souhaiteraient explorer ces sujets plus en détail peuvent consulter l’article suivant :

[Baldwin, Justin W., Katie Leap, John T. Finn, and Jennifer R. Smetzer. “Bayesian State-Space Models Reveal Unobserved off-Shore Nocturnal Migration from Motus Data.” Ecological Modelling 386 (October 24, 2018): 38–46.](https://doi.org/10.1016/j.ecolmodel.2018.08.006)
Des chercheurs proposent de nouveaux modèles espace-état bayésiens inspirés par la biologie de déplacements d’animaux dans le programme JAGS, lesquels intègrent des hypothèses éclairées relatives au comportement. Une simple routine de localisation basée sur le logiciel R bsam permet de prédire la position d’un oiseau et l’incertitude spatiale (géographique).

[Baldwin, Justin. “Modelling Bird Migration with Motus Data and Bayesian State-Space Models.” University of Massachusetts Amherst, 2017.](http://scholarworks.umass.edu/masters_theses_2/565)
Des chercheurs proposent de nouveaux modèles espace-état bayésiens de déplacements d’animaux inspirés par la biologie dans le programme JAGS, lesquels intègrent des hypothèses éclairées relatives au comportement. Les modèles sont évalués au moyen d’une étude de simulation puis sont appliqués par le recours à une routine de localisation sur un ensemble de données Motus dans le but d’estimer des positions et des comportements qui n’ont pas été observés.

[Janaswamy, Ramakrishna, Pamela H. Loring, and James D. McLaren. “A State Space Technique for Wildlife Position Estimation Using Non-Simultaneous Signal Strength Measurements.” ArXiv.org, May 28, 2018.](https://arxiv.org/pdf/1805.11171.pdf)
On combine un modèle de déplacement pour obtenir des trajectoires bien fondées du point de vue biologique sur un plan tridimensionnel et un modèle d’observation pour tenir compte de l’effet de la distance, de l’altitude et de l’angle de relèvement sur la puissance du signal reçu. Cette nouvelle technique de modélisation espace-état permet d’estimer les trajectoires des déplacements dans les airs d’émetteurs VHF dans le réseau Motus.

À mesure que des outils d’analyse et de modélisation plus évolués deviendront accessibles, nous les présenterons ici.

Nous encourageons fortement les participants à nous envoyer des exemples de scripts et de fonctions qui pourraient être intégrés au présent guide.
